version: '3.7'

services:
  db:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    command: sh -c "make migrate && python -m bot"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
    environment:
      - BOT_TOKEN
      - NGINX_HOST
    ports:
      - 3001:3001
  nginx:
    image: nginx:1.23-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      - NGINX_HOST
    volumes:
      - ./nginx/first_start/:/etc/nginx/templates/:ro
      # - ./nginx/templates/:/etc/nginx/templates/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:v2.5.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  pgdata: