"""Field lesson_date renamed -> date

Revision ID: 0bf8b9167f5c
Revises: 655007e7eb32
Create Date: 2024-12-23 19:58:18.052461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf8b9167f5c'
down_revision: Union[str, None] = '655007e7eb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regular_schedule', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('regular_schedule', 'lesson_date')
    op.add_column('uday_schedule', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('uday_schedule', 'lesson_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uday_schedule', sa.Column('lesson_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('uday_schedule', 'date')
    op.add_column('regular_schedule', sa.Column('lesson_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('regular_schedule', 'date')
    # ### end Alembic commands ###
