"""Initial revision

Revision ID: 5c26ed8114de
Revises: 
Create Date: 2024-12-06 11:20:11.148306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c26ed8114de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regular_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('lesson_info', sa.Text(), nullable=False),
    sa.Column('class_letter', sa.String(length=5), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uday_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('lesson_info', sa.Text(), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('class_letter', sa.String(length=5), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('u_group_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('uday_schedule')
    op.drop_table('regular_schedule')
    # ### end Alembic commands ###
