"""Created abstract Lesson model, Regular and Uday schedule inherited from Lesson

Revision ID: 655007e7eb32
Revises: abcaf8d7d2e9
Create Date: 2024-12-09 17:41:58.658710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655007e7eb32'
down_revision: Union[str, None] = 'abcaf8d7d2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
