"""all models are updated

Revision ID: cd68bca2ab29
Revises: 54cceba9a60d
Create Date: 2024-12-09 09:57:59.702485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd68bca2ab29'
down_revision: Union[str, None] = '54cceba9a60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regular_schedule', sa.Column('class_group', sa.Integer(), nullable=False))
    op.drop_column('regular_schedule', 'group_number')
    op.add_column('uday_schedule', sa.Column('uday_group', sa.Integer(), nullable=False))
    op.drop_column('uday_schedule', 'group_number')
    op.add_column('users', sa.Column('class_group', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('uday_group', sa.Integer(), nullable=False))
    op.drop_column('users', 'group_number')
    op.drop_column('users', 'u_group_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('u_group_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('group_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'uday_group')
    op.drop_column('users', 'class_group')
    op.add_column('uday_schedule', sa.Column('group_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('uday_schedule', 'uday_group')
    op.add_column('regular_schedule', sa.Column('group_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('regular_schedule', 'class_group')
    # ### end Alembic commands ###
